# Generated by Django 5.0.4 on 2024-04-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('fruit_descriptions', models.TimeField()),
                ('is_fresh', models.BooleanField(default=True)),
            ],
        ),
    ]
