# Generated by Django 5.0.4 on 2024-04-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_fruits_fruit_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruits',
            options={'ordering': ['-fruit_name'], 'verbose_name': 'home_fruits'},
        ),
        migrations.AlterUniqueTogether(
            name='fruits',
            unique_together={('fruit_name',)},
        ),
        migrations.AlterModelTable(
            name='fruits',
            table='home_fruits',
        ),
    ]
