# Generated by Django 5.0.4 on 2024-04-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_fruits_options_alter_fruits_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fruits',
            unique_together={('fruit_name', 'fruit_descriptions')},
        ),
    ]
