# Generated by Django 5.0.4 on 2024-04-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_fruits_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fruits',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='fruit_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='fruits',
            constraint=models.UniqueConstraint(fields=('fruit_name', 'fruit_descriptions'), name='unique_fruit_desc'),
        ),
    ]
